project:
  type: website
  output-dir: "docs"

website:
  title: "Ben Jepson"
  navbar:
    right:
      - text: "About"
        href: "about.qmd"
      - text: "LinkedIn"
        href: "https://linkedin.com/in/benjepson"

format:
  html:
    theme: cosmo
    toc: true



